quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
omgcluster:
  init:
    version: ${CLUSTER_VERSION}
  server:
    internal-address: ${INTERNAL_ADDRESS}
    external-address: ${EXTERNAL_ADDRESS}
