quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
  redis:
    hosts: ${REDIS_HOSTS}
omgcluster:
  init:
    version: ${INIT_VERSION}
  node:
    name: ${HOSTNAME}
  state:
    prefix: ${STATE_PREFIX}
    sim-state:
      ttl: ${SIM_STATE_TTL}
    zone-state:
      ttl: ${ZONE_STATE_TTL}
  tick:
    interval: ${TICK_INTERVAL}
