quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
  redis:
    hosts: ${REDIS_HOSTS}
omgcluster:
  init:
    version: ${INIT_VERSION}
  node:
    name: ${HOSTNAME}
  sim-result:
    prefix: ${quarkus.cache.redis.prefix}
    ttl: ${SIM_RESULT_TTL}
  zone-state:
    prefix: ${quarkus.cache.redis.prefix}
    ttl: ${ZONE_STATE_TTL}
  tick:
    interval: ${TICK_INTERVAL}
