quarkus:
  datasource:
    devservices:
      container-env:
        "PAGER": "cat"
  log:
    category:
      "sh.byv":
        level: DEBUG
omgcluster:
  init:
    version: 2
  server:
    name: localhost
  tick:
    interval: 1000
